export default {
  ZONES_RECEIVED: 'ZONES_RECEIVED',
  ZONE_CREATED: 'ZONE_CREATED',
  SELECT_ZONE: 'SELECT_ZONE',

  COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
  COMMENT_CREATED: 'COMMENT_CREATED'
};
